// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNFAEdzcPRD63xQW4gEJcREUc4OuJxh0',
    appId: '1:195841888078:web:3a1fa808c07fe18cfad81f',
    messagingSenderId: '195841888078',
    projectId: 'multi-marathon',
    authDomain: 'multi-marathon.firebaseapp.com',
    storageBucket: 'multi-marathon.firebasestorage.app',
    databaseURL:
        'https://multi-marathon-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNtGUaeik7Mz2VOLErxLO6iX4IjvMhqpo',
    appId: '1:195841888078:android:707dc232b3daa2e7fad81f',
    messagingSenderId: '195841888078',
    projectId: 'multi-marathon',
    storageBucket: 'multi-marathon.firebasestorage.app',
    databaseURL:
        'https://multi-marathon-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKQWO06nMD6PI4Jt6Cd2rGwHUzoUTxZ8Y',
    appId: '1:195841888078:ios:31b0c99272be7723fad81f',
    messagingSenderId: '195841888078',
    projectId: 'multi-marathon',
    storageBucket: 'multi-marathon.firebasestorage.app',
    iosBundleId: 'com.example.multiMarathon',
    databaseURL:
        'https://multi-marathon-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKQWO06nMD6PI4Jt6Cd2rGwHUzoUTxZ8Y',
    appId: '1:195841888078:ios:31b0c99272be7723fad81f',
    messagingSenderId: '195841888078',
    projectId: 'multi-marathon',
    storageBucket: 'multi-marathon.firebasestorage.app',
    iosBundleId: 'com.example.multiMarathon',
    databaseURL:
        'https://multi-marathon-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPNFAEdzcPRD63xQW4gEJcREUc4OuJxh0',
    appId: '1:195841888078:web:6c3010aad756965cfad81f',
    messagingSenderId: '195841888078',
    projectId: 'multi-marathon',
    authDomain: 'multi-marathon.firebaseapp.com',
    storageBucket: 'multi-marathon.firebasestorage.app',
    databaseURL:
        'https://multi-marathon-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}
